extends: default

data:
  winsorize_enabled: false
  features:
    - addr_state
    - term
    - home_ownership
    - verification_status
    - dti
    - purpose
    - emp_length
    - total_bc_limit
    - fico_range_high
    - fico_range_low
    - loan_amnt
    - bc_open_to_buy
